name: Draft PR

on:
  push:
    branches-ignore: [main]

permissions:
  contents: read

jobs:
  draft:
    uses: PineappleEmperor/release-flow/.github/workflows/auto-draft-pr.yml@91c33e48be6ff98c348ec71530d31e04fc6a53f4 # v1.0.0
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
