name: Testbed Coverage

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  coverage:
    uses: PineappleEmperor/release-flow/.github/workflows/testbed-coverage.yml@87305e56bf921fe8728a2b448b112b06da6cc082 # v1.1.1
