name: Testbed Coverage

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  coverage:
    uses: PineappleEmperor/release-flow/.github/workflows/testbed-coverage.yml@ca36eb9b5bae9840a119a2a6fc2f7628de90d1ba # v1.1.5
