name: Testbed Coverage

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  coverage:
    uses: PineappleEmperor/release-flow/.github/workflows/testbed-coverage.yml@7bfc333373cc6f5b396e0e786588e57dae033fdb # v1.1.3
